version: '3'

services:

    mydb:
        image: mysql:5.7
        ports:
            - 3306:3306
        restart: always
        volumes:
            - "./.data/db:/var/lib/mysql"
            - "./logs/:/var/log/"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dbase 
    php:
        image: php:latest
        ports:
            - 9000:9000
        expose:
            - "9000"
            - "9001"
        links:
            - mydb:mysqldb
        restart: always
        volumes:
            - ./www:/var/www/vhosts/site
            
    ngnix:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        expose:
                - "1234"
        restart: always
        links:
            - php
        volumes:
              
            - ./logs/nginx/:/usr/share/nginx/html
